- name: ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: ensure proxmoxer is installed
  pip:
    name: proxmoxer>=2.0.0
    state: latest

- name: create new VM with minimal configs
  vars:
    ansible_python_interpreter: /usr/bin/python3
  community.proxmox.proxmox:
    vmid: "{{ test_media_vmid }}"
    node: "{{ test_media_node }}"
    api_user: "{{ test_media_api_user }}"
    api_token_id: "{{ test_media_api_token_id }}"
    api_token_secret: "{{ test_media_api_token_secret }}"
    api_host: "{{ test_media_api_host }}"
    hostname: "{{ test_media_hostname }}"
    password: "{{ test_media_password }}"
    ostemplate: "{{ test_media_ostemplate }}"

